[env:esp32-c3-mini-gc9a1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = 
	lovyan03/LovyanGFX
	bblanchon/ArduinoJson
	tzapu/WiFiManager
	esp32async/ESPAsyncWebServer
build_flags = 
	-D LGFX_USE_V1
	-D BOARD_GC9A01_ROUND
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-s3-touch-lcd-2]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
lib_deps = 
    lovyan03/LovyanGFX
    bblanchon/ArduinoJson
    tzapu/WiFiManager
    esp32async/ESPAsyncWebServer
build_flags = 
    -D LGFX_USE_V1
    -D BOARD_LCD2_ST7789
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM