[env:esp32-c3-mini-gc9a1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
    lovyan03/LovyanGFX@^1.2.7
    bblanchon/ArduinoJson@^7.2.0
    tzapu/WiFiManager

build_flags =
    -D LGFX_USE_V1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1